### ISSUE TITLE
App Doesn't work with new web address

### ISSUE THREAD

**Issue by subhogue** [atla5/SWEN-344-WebEngProject#15]
on All three productions, pressing the sign in button redirects you to 'http://fierce-lowlands-94356.herokuapp.com/auth/twitter' which no longer exists. I'll be looking into fixing this.

**Comment by subhogue** [comment]
The offending code is in 'app/views/index.html.erb' It appears that this is an issue in which environment we send it to as we currently have the address to go to hard-coded to  'http://fierce-lowlands-94356.herokuapp.com/auth/twitter' If the address remains hard-coded then it will require us to change the address, depending on the launch target, to one of the following:
     'http://twitterstocks-dev.herokuapp.com/auth/twitter'
     'http://twitterstocks-stg.herokuapp.com/auth/twitter'
     'http://twitterstocks.herokuapp.com/auth/twitter'

**Comment by subhogue** [comment]
After digging around I believe to fix this we need to add a line like " get '/auth/twitter', to:??????, as: 'signin' " to the file 'routes.rb'. We then should be able to replace the current hard-coded address with a link-to command if I'm understanding that correctly.

**Comment by aaron13michael** [comment]
I need to register the 3 apps with twitter and change the configured URL in
the Twitter account. I addressed the issue during our last team meeting.

**Comment by subhogue** [comment]
oh, okay, I didn't see that in the meeting minutes, maybe I missed it. I guess I'll leave the issue open till it is fixed but good to know what is going on.
