### ISSUE TITLE
Write control functions (with tests) for generating and executing transactions

### ISSUE THREAD

**Issue by atla5** [atla5/SWEN-344-WebEngProject#20]
-Create functionality for creating and executing transactions (buy, sell).
-create unit tests for these as well.

**Comment by aaron13michael** [comment]
I'd prefer that we use the bug tracker only for bugs and not tasks that need to be completed

**Comment by atla5** [comment]
we included this on the to-do section of the past two meetings. we can mark bugs with the 'bug' tag and filter to that.
